# Generated by Django 3.1.1 on 2020-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200926_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentpacket',
            name='visited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
