# Generated by Django 3.1.1 on 2020-09-26 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_uservisitinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 27, 0, 54, 8, 175528)),
        ),
    ]
