# Generated by Django 3.1.1 on 2020-09-26 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200927_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 1, 0, 14, 831982)),
        ),
    ]
