# Generated by Django 3.1.1 on 2020-09-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200927_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
