# Generated by Django 3.1.1 on 2020-09-27 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200927_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 27, 14, 26, 17, 881736), max_length=100),
        ),
    ]
