# Generated by Django 3.1.1 on 2020-09-27 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200927_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpacket',
            name='grabbedlink',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 27, 17, 43, 43, 293113), max_length=100),
        ),
    ]
