# Generated by Django 3.1.1 on 2020-09-28 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200927_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisitinghistory',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uservisitinghistory',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 8, 41, 10, 338522), max_length=100),
        ),
    ]
