# Generated by Django 3.1.1 on 2020-09-28 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200928_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentpacket',
            name='packetitemremaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 9, 37, 43, 569724), max_length=100),
        ),
    ]
