# Generated by Django 3.1.1 on 2020-09-28 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200928_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentpacket',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 11, 37, 33, 488851), max_length=100),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 11, 37, 33, 488851), max_length=100),
        ),
    ]
