# Generated by Django 3.1.1 on 2020-09-28 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200928_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpacket',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 15, 49, 48, 157186), max_length=100),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visited_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 15, 49, 48, 157186), max_length=100),
        ),
    ]
