# Generated by Django 3.1.1 on 2020-09-28 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200928_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpacket',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 19, 1, 54, 747037), max_length=100),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 19, 1, 54, 748031), max_length=100),
        ),
    ]
