# Generated by Django 3.1.1 on 2020-09-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200928_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpacket',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-29 16:19:18', max_length=100),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 29, 16, 19, 18, 305074), max_length=100),
        ),
    ]
