# Generated by Django 3.1.1 on 2020-10-01 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20200930_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimtank',
            name='submittion_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currentpacket',
            name='packet_creation_time',
            field=models.CharField(default='2020-10-01 07:57:18', max_length=100),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 10, 1, 7, 57, 18, 122674), max_length=100),
        ),
    ]
