# Generated by Django 3.1.1 on 2020-10-01 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20201001_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.CharField(default=datetime.datetime(2020, 10, 1, 18, 49, 44, 654218), max_length=100),
        ),
    ]
