# Generated by Django 3.1.1 on 2020-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20201001_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimtank',
            name='alloted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='visiting_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
