# Generated by Django 3.1.1 on 2020-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_claimtank_tempid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitinghistory',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
