# Generated by Django 3.1.1 on 2020-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_uservisitinghistory_pure_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimtank',
            name='raw_link',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='claimtank',
            name='claimed_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
