# Generated by Django 2.0 on 2020-09-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
