# Generated by Django 2.0 on 2020-09-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0002_auto_20200921_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verfied', models.BooleanField(default=False)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
