# Generated by Django 2.2.4 on 2020-09-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_x'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
