# Generated by Django 2.2.4 on 2020-09-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x',
        ),
    ]
