# Generated by Django 2.2.4 on 2020-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
