# Generated by Django 2.2.4 on 2020-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20200922_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kind',
            field=models.CharField(choices=[('up', 'Up')], default='', max_length=7),
        ),
    ]
