# Generated by Django 2.2.4 on 2020-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_profile_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kind',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=7),
        ),
    ]
