# Generated by Django 3.1.1 on 2020-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20200924_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
