# Generated by Django 3.1.1 on 2020-09-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
