# Generated by Django 3.1.1 on 2020-09-24 03:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20200924_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_nominals',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
    ]
