# Generated by Django 3.1.1 on 2020-09-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_auto_20200924_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='post_nominals',
            new_name='data',
        ),
    ]
