# Generated by Django 3.1.1 on 2020-09-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_auto_20200924_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
