# Generated by Django 3.1.1 on 2020-09-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_remove_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurlssrepository',
            name='submitted_url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
