# Generated by Django 3.1.1 on 2020-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_auto_20200924_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
