# Generated by Django 3.1.1 on 2020-09-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_auto_20200925_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_packetID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_packet_completed',
            field=models.BooleanField(default=False),
        ),
    ]
