# Generated by Django 3.1.1 on 2020-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_auto_20200926_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_packetlength',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
