# Generated by Django 3.1.1 on 2020-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_profile_current_packetlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
