# Generated by Django 3.1.1 on 2020-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_auto_20200926_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
