# Generated by Django 3.1.1 on 2020-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_auto_20200927_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_packet_completed',
            field=models.BooleanField(default=True),
        ),
    ]
