# Generated by Django 3.1.1 on 2020-09-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_auto_20200927_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentpacketitemsremaining',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
