# Generated by Django 3.1.1 on 2020-09-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_profile_packet_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalitemsvisited',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 12, 55, 36, 658032), max_length=100),
        ),
    ]
