# Generated by Django 3.1.1 on 2020-09-28 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_auto_20200928_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 15, 49, 48, 155192), max_length=100),
        ),
    ]
