# Generated by Django 3.1.1 on 2020-09-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_auto_20200928_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='totalitemsvisited',
            new_name='packetitemsvisited',
        ),
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 16, 18, 38, 296127), max_length=100),
        ),
    ]
