# Generated by Django 3.1.1 on 2020-09-28 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_auto_20200928_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claimable_links',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 18, 45, 24, 377963), max_length=100),
        ),
    ]
