# Generated by Django 3.1.1 on 2020-09-28 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_auto_20200928_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalregisteredvisits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 19, 1, 54, 745991), max_length=100),
        ),
    ]
