# Generated by Django 3.1.1 on 2020-09-28 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_auto_20200928_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default=datetime.datetime(2020, 9, 28, 20, 38, 25, 43047), max_length=100),
        ),
    ]
