# Generated by Django 3.1.1 on 2020-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_auto_20200928_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-28 22:54:34', max_length=100),
        ),
    ]
