# Generated by Django 3.1.1 on 2020-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0049_auto_20200929_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-29 18:53:27', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
