# Generated by Django 3.1.1 on 2020-09-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0052_auto_20200929_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-30 01:33:20', max_length=100),
        ),
    ]
