# Generated by Django 3.1.1 on 2020-09-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0053_auto_20200930_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remaining_balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-30 09:19:26', max_length=100),
        ),
    ]
