# Generated by Django 3.1.1 on 2020-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0054_auto_20200930_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.CharField(default='2020-09-30 20:32:47', max_length=100),
        ),
    ]
