# Generated by Django 3.1.1 on 2020-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0057_auto_20201001_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packet_creation_time',
            field=models.IntegerField(),
        ),
    ]
