# Generated by Django 3.1.1 on 2020-10-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0060_auto_20201001_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='packet_creation_time',
        ),
    ]
