# Generated by Django 3.1.1 on 2020-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0063_auto_20201001_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit_time',
            field=models.IntegerField(default=0),
        ),
    ]
