# Generated by Django 3.1.1 on 2020-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0064_profile_last_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalclaimedtraffic',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totaltrafficreturnedback',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
